In [1]:
import numpy as np

# Define matrix A
A = np.array([[3, 5, 9], [3, 3, 4], [5, 9, 17]])

# Define matrix B
B = np.array([[2], [1], [4]])

# Solve the matrix equation Ax=B for x
x = np.linalg.solve(A, B)

# Print the result
print(x)


[[ 1.]
 [-2.]
 [ 1.]]


In [2]:
import numpy as np

# Define the input arrays
arrayOne = np.array([[5, 6, 9], [21, 18, 27]])
arrayTwo = np.array([[15, 33, 24], [4, 7, 1]])

# Add the arrays
resultArray = arrayOne + arrayTwo

# Calculate the square of each element in the resulting array
resultArray = np.square(resultArray)

# Print the resulting array
print(resultArray)


[[ 400 1521 1089]
 [ 625  625  784]]


In [3]:
import numpy as np

# Define the 2-D array
sampleArray = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])

# Find the maximum element from axis 0
maxAxis0 = np.max(sampleArray, axis=0)
print("Maximum element from axis 0:", maxAxis0)

# Find the minimum element from axis 1
minAxis1 = np.min(sampleArray, axis=1)
print("Minimum element from axis 1:", minAxis1)


Maximum element from axis 0: [82 94 73]
Minimum element from axis 1: [34 12 53]


In [5]:
import numpy as np

# Define the input arrays
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

# Get the positions where elements of a and b match
matches = np.where(a == b)[0]

# Print the result
print(matches)


[1 3 5 7]


In [6]:
import numpy as np

# Define matrices a and b
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Obtain matrix c
c = np.vstack((a, b))

# Obtain matrix d
d = np.hstack((a, b))

# Print the resulting matrices
print("Matrix c:")
print(c)
print("\nMatrix d:")
print(d)


Matrix c:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Matrix d:
[[1 2 5 6]
 [3 4 7 8]]
